### ISSUE TITLE
Add plugin to cssnext

### ISSUE THREAD

**Issue by ai** [JLHwung/postcss-font-family-system-ui#2]
It is hard to find good PostCSS plugins, so you should add plugin to cssnext plugin preset

**Comment by JLHwung** [comment]
Raised PR on https://github.com/MoOx/postcss-cssnext/pull/342, thanks.

**Comment by JLHwung** [comment]
Closed as https://github.com/MoOx/postcss-cssnext/pull/342 is merged.
