### ISSUE TITLE
No valid exports main found

### ISSUE THREAD

**Issue by francoisromain** [JLHwung/postcss-font-family-system-ui#260]
Hello and thank you for this great plugin. 

I have updated to the latest version of this plugin which I see is now "100% esm ready". 
It now makes an error in my actual config where it is imported like so: 

```js
module.exports = {
  plugins: [
    require("postcss-font-family-system-ui")
  ]
};
```
Which is loaded by webpack's css-loader. 

The error is: `No valid exports main found`. 

How can I make this work? 

thank you

**Comment by AfzalivE** [comment]
@francoisromain try updating your node version

**Comment by JLHwung** [comment]
@francoisromain I can not reproduce this error on Node.js 14 Please upgrade your node.js version to latest LTS, which have proper ESM support.

The ESM in node is still experimental. This package always track latest supported node.js versions, which means it may break on an older unsupported version, i.e. v13.
