### ISSUE TITLE
Treat "@std/esm" as dependency

### ISSUE THREAD

**Issue by AngusFu** [JLHwung/postcss-font-family-system-ui#27]
Probably, we should treat "@std/esm" as a dependency, not devDenpendency.  Otherwise, `@std/esm` may not get installed when executing `npm install --save-dev` or `yarn add --dev`.

![image](https://user-images.githubusercontent.com/8180186/33005881-fb1104e4-ce02-11e7-9422-7f6e3b63e96a.png)

**Comment by JLHwung** [comment]
@AngusFu Good catch! We will need `@std/esm` since we don't build code now.

**Comment by AngusFu** [comment]
@JLHwung  :+1:  真快啊哈哈
