### ISSUE TITLE
Send PR to plugins lists

### ISSUE THREAD

**Issue by ai** [JLHwung/postcss-font-family-system-ui#3]
Great plugin. You should add it to 2 main PostCSS plugins list:

1. `docs/plugins.md` in PostCSS repo.
2. https://github.com/himynameisdave/postcss-plugins#submiting-a-plugin

**Comment by JLHwung** [comment]
> docs/plugins.md in PostCSS repo.
https://github.com/postcss/postcss/pull/959

> https://github.com/himynameisdave/postcss-plugins#submiting-a-plugin
https://github.com/himynameisdave/postcss-plugins/pull/171

Thank you so much for suggesting PR to plugins lists.

**Comment by JLHwung** [comment]
Closed as dependent PR is merged.
