### ISSUE TITLE
 TypeError: require(...) is not a function

### ISSUE THREAD

**Issue by BlazerYang** [JLHwung/postcss-font-family-system-ui#39]
my project is running while in windows, but when i deploy my project to Ubuntu 15.1 and run npm install , then use npm run dev, but build is broken as the reason in title
As  I see in the trackback, it seems like require("postcss-font-family-system-ui") return undefined in
./node_modules/[postcss-cssnext]/lib/features.js:97:52
```js
  fontFamilySystemUi: function fontFamilySystemUi(options) {
    return require("postcss-font-family-system-ui")(options);
  }
```
after i comment this three line, things seem back to normal, so what is really happened here

**Comment by JLHwung** [comment]
A recent update of `@std/esm` breaks `postcss-font-family-system-ui`. See https://github.com/standard-things/esm/issues/239

Will release a patch release to bump dependency versions.
