### ISSUE TITLE
index.bundle.js is missing and everything is broken!

### ISSUE THREAD

**Issue by gera2ld** [JLHwung/postcss-font-family-system-ui#41]
In v3.0.0, `index.bundle.js` is missing and everything is broken!

```
import postcss from 'postcss';
^^^^^^

SyntaxError: Unexpected token import
```

**Comment by JLHwung** [comment]
🤔 interesting. I cannot reproduce this issue though. I download the tarball manually and it looks good to me. The `index.bundle.js` is as-is.

@gera2ld What is the terminal output of
```bash
wget https://registry.npmjs.org/postcss-font-family-system-ui/-/postcss-font-family-system-ui-3.0.0.tgz -O- | tar -zxvf -
```

**Comment by gera2ld** [comment]
Because `postcss-preset-env` is requiring `postcss-font-family-system-ui` from GitHub:
![image](https://user-images.githubusercontent.com/3139113/35181798-854e46f0-fe03-11e7-860e-36706346388b.png)

And resolved to this file: <https://codeload.github.com/jonathantneal/postcss-font-family-system-ui/tar.gz/6f7e271b2deda3ed38a7cc1fd602ecf408d15668>, which has no `index.bundle.js` in it.

**Comment by gera2ld** [comment]
Maybe I should file an issue in `postcss-preset-env`?

**Comment by JLHwung** [comment]
@gera2ld @jonathantneal This is not an issue of `postcss-font-family-system-ui`. I have filed https://github.com/jonathantneal/postcss-preset-env/pull/4. Thanks for reminding.
