### ISSUE TITLE
Why did you publish an ES6 module with import/export?

### ISSUE THREAD

**Issue by MoOx** [JLHwung/postcss-font-family-system-ui#42]
This is a breaking change you didn't mention.
This is a big deal for retrocompat. export are a syntax error in all node environment.
A es5 version (at least for import/export) is mandatory imo in the actual stage of es6 implementation in node.
Care to fix this or provide an escape hatch?

**Comment by MoOx** [comment]
Pretty sure I will have tons of issue about this change introduced in postcss-cssnext 3.1.0...

**Comment by JLHwung** [comment]
Hi MoOx,

The `index.js` is not the entry file of this package. `postcss-font-family-system-ui` uses `rollup` to generate a CommonJS module `index.bundle.js` for backward compatibility. It is not, and should not be, in the source control.

You can check by
```bash
wget https://registry.npmjs.org/postcss-font-family-system-ui/-/postcss-font-family-system-ui-3.0.0.tgz -O- | tar -zxvf - && cat package/index.bundle.js
```

Let we know if there is any feedback on node compatibility.

**Comment by MoOx** [comment]
I guess it's webpack that resolve to index.js then. Will see from my side. Sorry for this issue.

**Comment by JLHwung** [comment]
While we offer `index.bundle.js` as the `main` entry, we do set `module: "index.js"` in the meta information and we are meant to. Please use any ES6 module-loader to load `index.js`.

On webpack you can check `resolve.mainFields` settings.
