### ISSUE TITLE
Part of the font stack duplicates when using the `postcss-modules` plugin

### ISSUE THREAD

**Issue by chris-pearce** [JLHwung/postcss-font-family-system-ui#60]
This is a weird one, when using the [`postcss-modules`](https://github.com/css-modules/postcss-modules) plugin it causes the font stack (except for the `system-ui, -apple-system` families) to be duplicated:

```css
font-family: 'sofia-pro', system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Droid Sans, Helvetica Neue, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Droid Sans, Helvetica Neue;
```

I'm trying to create an isolated sandbox so you can see the issue.

**Comment by JLHwung** [comment]
Hi chris-pearce,

Could you list the postcss packages you have installed, this can help isolating the problem. Note that you can use the following command to help
```
find node_modules -name "postcss-*" -depth 1
```

**Comment by JLHwung** [comment]
Closed as no response for 15 days, feel free to reopen it if you have any further discoveries.
