### ISSUE TITLE
Plugin doesn't handle values of CSS custom property

### ISSUE THREAD

**Issue by huston007** [JLHwung/postcss-font-family-system-ui#65]
If we have font-family stored in CSS custom property like:
```
:root {
  --my-font-family: system-ui, Arial, sans-serif;
}
```

Plugin lefts this value unchanged.

In details, we use `postcss-font-family-system-ui` plugin as a part of `postcss-cssnext` with `postcss-custom-properties` plugin

Looks like the reason is that plugin applies only [if property called exactly "font-family"](https://github.com/JLHwung/postcss-font-family-system-ui/blob/master/index.js#L39). Maybe this could be relaxed or configurable

**Comment by JLHwung** [comment]
Hi Andrey,

Thanks for reaching out. I never thought of this kind of usage before.

The postcss-cssnext will apply `postcss-css-custom-properties` before `postcss-font-family-system-ui`. As `postcss-css-custom-properties` will use `browserlists` to determine whether it should replace `var(--my-font-family)` with `system-ui`, chances are `postcss-css-custom-properties` will not replace custom properties when the browser is advanced enough, and thus `system-ui` is not polyfilled as you know. You can reproduce the behaviours [here](https://preset-env.cssdb.org/playground) by switching `> 1%` and `> 5%` browserlists query. 

It comes to me there is at least two approaches to attack this problem.

a. Add `properties` option to specify, if any, extra properties to polyfill other than `font` and `font-family`

(Note: The following example are proposal only)
```js
postcssSystemUiFont({
  properties: ["--my-font-family"]
})
```

b. Scan all custom properties(any CSS properties starts with `--`) to polyfill any `system-ui` keywords if existed. The API interface is unchanged.

Pros and Cons I can expect:

|  | Pros | Cons |
| ---| --- | --- |
| a) | minimal performance overhead |  <li>need to revise configuration if code is refactored</li><li> another option to toggle </li> |
| b) | works out of box | some performance overhead on cases of heavy custom properties usage |

Personally I am lean to b) approach if the performance overhead is accepted. What do you think? @huston007

**Comment by huston007** [comment]
@JLHwung Hello and thank you for the great response! I also like "b" option since it looks much more straight-forward. I'd even say that it is less expectable that only properties with "font-family" name are covered with the plugin than "b" option.

As for performance penalty – I don't think it takes a lot to check if AST node is CSS custom property, and there shouldn't be really many properties in even big project. Like 50, 100? I don't think more than 100.
